# Generated by Django 5.0.6 on 2024-05-24 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("full_name", models.CharField(max_length=200)),
                (
                    "alignment",
                    models.CharField(
                        choices=[("L", "Light Side"), ("D", "Dark Side")], max_length=1
                    ),
                ),
                ("home_planet", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Lightsaber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("color", models.CharField(max_length=20)),
                ("design", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lightsaber",
                        to="app.character",
                    ),
                ),
            ],
        ),
    ]
