# Generated by Django 5.0.6 on 2024-05-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_character_profile_image_lightsaber_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='lore',
            field=models.TextField(default="Details about the character's backstory, significant events, and role in the Star Wars universe."),
        ),
    ]
