# Generated by Django 5.0.6 on 2024-05-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_character_lore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightsaber',
            name='description',
        ),
    ]
