# Generated by Django 5.0.6 on 2024-05-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_lightsaber_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightsaber',
            name='description',
            field=models.TextField(default="Details about the lightsabers's backstory, significant events, and role in the Star Wars universe."),
        ),
    ]
